### ISSUE TITLE
How to persist the data

### ISSUE THREAD

**Issue by Fazerty** [BetterVoice/postgresql-container#1]
Hi,
I'm a new user of Docker.
When I stop and then restart a postgresql-container where I've created some data, these data are lost.
I don't know how to persist the data created in the database or databases (when I use a master and a slave).
Many Thanks

**Comment by Fazerty** [comment]
I tried to run the container with this option: -v /postgresdata:/var/lib/postgresql
but when the container is restarted the newly created folder in /postgresdata/9.3/main/base is removed.

**Comment by Fazerty** [comment]
Same problem if I try like this
docker run --name dbdata postgres echo "Data-only container for postgres"
docker run --name postgresql -p 5520:5432/tcp --volumes-from dbdata bettervoice/postgresql-container:9.3

**Comment by thomasquintana** [comment]
We have added a PG_INIT environment variable that when set to False will just start the service and will not re-initialize the container. Please refer to the README and the commit below. Hope this helps.

https://github.com/BetterVoice/postgresql-container/commit/c4ca28fded5702f76265219718d94e4eff2d223b

**Comment by thomasquintana** [comment]
I will give you a few takeaways on why things are done the current way. At BetterVoice, for every production deployment we always use at least two containers on separate machines composed of master/slave pairs. We typically don't have to restart our instances but if for some reason the master went down the slave would become the new master and we would discard the original master. Then we can just create a new slave to the new master. It's important to prevent the original master from restarting after fail-over, or you will end up with a "split brain" problem and data loss. There is a substantial body of literature on this, and third-party tools, so we won't discuss them here in detail. PG_INIT is just so you can stop and start a container that has already been initialized. If you have data you want to use from another container you can try the following:
- Create a new container with PG_INIT set to True and don't mount the volume with the data you would like to use.
- Stop the container.
- Restart the container with volume you would like to use mounted and PG_INIT set to False.

Best,
The BetterVoice Team

**Comment by Fazerty** [comment]
Could you describe how do you do that: the slave would become the new master?

Many Thanks!

**Comment by thomasquintana** [comment]
@Fazerty I apologize I missed your question. In hopes that it will still be helpful I will explain below.

When a container is configured as a slave it starts a [heartbeat](https://github.com/BetterVoice/postgresql-container/blob/master/bin/heartbeat.template) to determine if the master is still up and if it detects that the master is down it will promote the slave to be the new master. We run on our infrastructure on GCE so we actually have a [custom heartbeat](https://github.com/BetterVoice/gce-heartbeat/tree/gce-pgsql-hearbeat) that is not as trivial and on top of promoting the slave it moves the elastic IP over to the slave so there is 0 down time. Once the failover happens you want to discard the original master to avoid split brain problem and you can just bring up another slave and point it at the new master. Which allows you to keep failing over indefinitely.

Best,
The BetterVoice Team
